service: tankbot-serverless

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  role: arn:aws:iam::562692320777:role/slackbot
  deploymentMethod: direct
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    SLACK_APP_TOKEN: ${env:SLACK_APP_TOKEN}

functions:
  slack:
    handler: app.handler
    events:
      - http:
         path: slack/events
         method: post
         cors: true
         private: true

package:
  individually: true
  exclude:
    - node_modules/**
    - package-lock.json


